//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_ByCategory
    {
        public long ID { get; set; }
        public long ISBN { get; set; }
        public long Id_Category { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Category Category { get; set; }
    }
}
