//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Book_ByCategory = new HashSet<Book_ByCategory>();
        }
    
        public long ISBN { get; set; }
        public long Id_Author { get; set; }
        public long Id_Editorial { get; set; }
        public string Book_Name { get; set; }
        public Nullable<int> Quantity_Books { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Quantity_Page { get; set; }
        public System.DateTime date_entry { get; set; }
        public Nullable<System.DateTime> date_print { get; set; }
        public byte[] Doc_Data { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Book_ByCategory> Book_ByCategory { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
