//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Book_ByCategory = new HashSet<Book_ByCategory>();
        }
    
        public long Id_Category { get; set; }
        public string Category_Name { get; set; }
    
        public virtual ICollection<Book_ByCategory> Book_ByCategory { get; set; }
    }
}
